model:
  name: "vgg"
  loss_fn: "ce"
  arch_name: "D"  # choose vgg architecture: A, A-LRN, B, C, D

  # VGG architecture ( [num_convs, out_channels])
  vgg_cfgs:
    # VGG-11
    A:
      - [1, 64]
      - [1, 128]
      - [2, 256]
      - [2, 512]
      - [2, 512]
    
    # VGG-11 + LRN
    A-LRN:
      - [1, 64]
      - [1, 128]
      - [2, 256]
      - [2, 512]
      - [2, 512]
    
    # VGG-13
    B:
      - [2, 64]
      - [2, 128]
      - [2, 256]
      - [2, 512]
      - [2, 512]
    
    # VGG-16
    C:
      - [2, 64]
      - [2, 128]
      - [3, 256]
      - [3, 512]
      - [3, 512]
    
    # VGG-19
    D:
      - [2, 64]
      - [2, 128]
      - [4, 256]
      - [4, 512]
      - [4, 512]

