aug:
  train:
    - type: "RandomResizedCrop"
      size: ${task.img_size}
      scale: [0.6, 1.0]
    - type: "RandomHorizontalFlip"
      p: 0.5
    - type: "ToTensor"
    - type: "Normalize"
      mean: [0.485, 0.456, 0.406]
      std:  [0.229, 0.224, 0.225]
  val:
    - type: "Resize"
      size: ${task.img_size}
    - type: "CenterCrop"
      size: ${task.img_size}
    - type: "ToTensor"
    - type: "Normalize"
      mean: [0.485, 0.456, 0.406]
      std:  [0.229, 0.224, 0.225]
