task:
  name: "cifar10"
  data_root: "data/cifar10"
  img_size: 224   # we upscale to 224 to reuse backbones
  num_classes: 10
  class_names: ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]
