seed: 42
device: "cuda"   # or "cuda"
num_workers: 4
batch_size: 128 #64
epochs: 250 #100
lr: 1e-2
amp: true
output_root: "experiments"
save_best_metric: "val_acc"

early_stopping:
  patience: 50       # Number of epochs with no improvement after which training will be stopped
  min_delta: 0.001    # Minimum change to qualify as an improvement
